config/routes.rb
Votekey::Application.routes.draw do
  resources :users
  resource :user_session
  root :controller => "user_sessions", :action => "new"
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Successfully logged in."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "Successfully logged out."
    redirect_to root_url
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<% form_for(@user_session) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/new.html.erb
<% form_for @user_session do |f| %>
  <%= f.error_messages %>
  <br />
  <%= f.label :email %><br />
  <%= f.text_field :email %>
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %>
  <br />
  <%= f.submit "Submit" %>
<% end %>

<br class="clear" />
<%= link_to("Register", :controller => "users", :action => "new") %>

app/views/user_sessions/show.html.erb
<p>
  <b>Username:</b>
  <%=h @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%=h @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>